services:  
  web_app:
    build:
      context: ./src/
      dockerfile: web_app/Dockerfile
    restart: on-failure
    ports:
      - "80:80"
    env_file: .env

  file_parser:
    build:
      context: ./src/
      dockerfile: file_parser/Dockerfile
    restart: on-failure
    ports:
      - "5000:5000"
    volumes:
      - ../ztm_files:/bimba/ztm_files
    env_file: .env

  rest_api:
    build:
      context: ./src/
      dockerfile: rest_api/Dockerfile
    restart: on-failure
    ports:
      - "5001:5001"
    env_file: .env

  db:
    image: postgres:14
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ../postgres_data/postgres:/var/lib/postgresql/data
    env_file: .env

  neo4j_db:
    image: neo4j:4.1.4-community
    restart: on-failure
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ../neo4j_data/data:/data
    environment:
      - .env