services:
  web:
    build: ./app/
    ports:
      - "5000:5000"
  neo4j:
    build: ./neo4j_db/
    ports:
      - "5001:5001"
    env_file: .env
  db:
    image: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data/postgres:/var/lib/postgresql/data
    env_file: .env