services:  
  file_parser:
    build:
      context: ./src/
      dockerfile: file_parser/Dockerfile
    restart: on-failure
    ports:
      - "5000:5000"
    volumes:
      - ../ztm_files:/bimba/ztm_files
    env_file: .env

  rest_api:
    build:
      context: ./src/
      dockerfile: rest_api/Dockerfile
    restart: on-failure
    ports:
      - "5001:5001"
    env_file: .env
  
  web_app:
    build:
      context: ./src/
      dockerfile: web_app/Dockerfile
    restart: on-failure
    ports:
      - "5002:5002"
    env_file: .env

  db:
    image: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ../postgres_data/postgres:/var/lib/postgresql/data
    env_file: .env
