"""Add requests table

Revision ID: 702d5deb5180
Revises: fcd2d159e842
Create Date: 2022-11-14 19:15:12.941647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702d5deb5180'
down_revision = 'fcd2d159e842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=False),
    sa.Column('form_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###
