name: Deploy to production

env:
  PYTHON_VERSION: '3.10'

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    environment:
      name: production
      url: http://bimba.wdebsqi.pl/

    steps:
      - uses: actions/checkout@v3
      
      - name: Create .env file
        run: |
          touch .env
          echo HOST="${{ secrets.HOST }}" >> .env
          echo NEO4J_URL="${{ secrets.NEO4J_URL }}" >> .env
          echo NEO4J_USERNAME="${{ secrets.NEO4J_USERNAME }}" >> .env
          echo NEO4J_PASSWORD="${{ secrets.NEO4J_PASSWORD }}" >> .env
          echo NEO4J_AUTH="${{ secrets.NEO4J_AUTH }}" >> .env
          echo POSTGRES_USER="${{ secrets.POSTGRES_USER }}" >> .env
          echo POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo POSTGRES_DB="${{ secrets.POSTGRES_DB }}" >> .env
          echo POSTGRES_URL="${{ secrets.POSTGRES_URL }}" >> .env
          echo ZTM_FILES_DIRECTORY="${{ secrets.ZTM_FILES_DIRECTORY }}" >> .env
          echo TZ=Europe/Warsaw >> .env
          sed -i -e 's/\\//g' .env
          
      - name: Pack repository to .tar file
        run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf deploy.tar ../build/
        
      - name: Copy .tar file to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "deploy.tar"
          target: "~/bimba"
          
      - name: Unpack the build, build Docker images and restart containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: | 
            cd ~/bimba
            rm -rf build
            tar xvf deploy.tar
            cd build
            docker compose down
            docker rmi $(docker images -q -f reference='build-*')
            docker compose up -d
