name: Deploy Python app to VPS

env:
  PYTHON_VERSION: '3.10'

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Pack repository to .tar file
        run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf deploy.tar ../build/
        
      - name: Copy .tar file to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "deploy.tar"
          target: "/home/bimba"
          
      - name: Unpack the build and run the app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: cd /home/bimba && tar xvf deploy.tar && python3 build/run.py
